### ISSUE TITLE
add awardees

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/repronim.org#46]
https://www.repronim.org/fellowship.html

**Comment by juliebates** [comment]
Also just discussed the gallery question with Dave - his suggestion, would it simplify things and be possible to make screen shots  _per_ **Awardee year gallery**,  for example, rather than trying to get each photo/headshot separately?  Even if more limited functionality, he just would be glad to have some images for the Fellows. (if possible). There are 4 classes:
2024 Awardees
2022 Awardees
2020-2021 Awardees
2019-2020 Awardees
