### ISSUE TITLE
Port over Collaborating project page

### ISSUE THREAD

**Issue by asmacdo** [ReproNim/repronim.org#57]
From https://www.repronim.org/community.html#collaborating-projects to /about/collaborators port over collaborating projects and service projects.

**Comment by juliebates** [comment]
I know there is a potential bit of redundancy with the Community/Participate headers on the page, but my intention was to include the entire page (per above link) from the current site, because the text is relevant and includes mention of the two grant mandated types of collaborations (Collaborating and Service Projects). An easy tweak might be for me to just remove the Community header and replace it with Collaborators. That would alilgn with your menu bar descriptors on the left margin. Let me know what you think about that, I can go in and do a quick html edit on the current site page,
Regarding the sub-components of that page, I think the page could stand on its own (as is currently the case on active site) and not worry about introducing any additional/separate sub-section tags for the two types of project. I know my text doc included those, but that was a reminder reference that all of that content was in the single page to be ported over.

**Comment by asmacdo** [comment]
Ok we can include that -- feel free to make the edit to the current site if you like, but its not strictly necessary, we can make that edit when we port. 

I assume we also want to keep all the logos at the top?

**Comment by juliebates** [comment]
OK, I'll try a test edit of just the header, and see how it looks, if it doesn't look right, I can just delete my little test branch, but it seems like it makes sense to align the page title with the menu bar and the content for now...and if someone wants something different later, that's ok too. I'll let you know though, if/once  I make the change. 

yes please, keep the logos!

**Comment by juliebates** [comment]
OK- I changed the header on the page TO 'Collaborators' 

all set now
