### ISSUE TITLE
TODO:  Participate section

### ISSUE THREAD

**Issue by memartone** [ReproNim/repronim.org#66]
Check with Julie.

**Comment by juliebates** [comment]
Just discussed some things with Dave - this should be coming shortly, I'll keep you posted

**Comment by juliebates** [comment]
I'm going to try and paste my full suggested page content below, let's all cross our fingers! 
I'm not sure, you may need this in a different form, but I'll try it here. A couple of notes- one,  I used **bold blue** for anything that has an intended hyperlink, in my own word doc, but it doesn't copy over here, so I just added boldface right in this window for each of those below, and have provided the respective links for each of those items. The only items that don't include links are the two  Calendar items. I used bold (in black, in my document) to make the calendar items readily visible. Two, (as in second note) I did remove a couple of items from the list as you had it on the devsite page. Let me know if you want me to identify those lines -- they are excluded from my content below. I'm not sure if the formating will carry over, but let's see. RE: the webinars item, I changed the wording for this page, on Dave's request, to 'Follow our Webinar series' - but note too that I linked it to the Webinars page in this case, also at his request, because the page has upcoming webinar listings, which makes it useful as used here in the calendar section.

Participate


**Contact us**
	[Clickable for email, if possible, TO:]  [info@repronim.org](mailto:info@repronim.org)

•	[**The ReproNim Blog**](https://repronim.wordpress.com/)
Link: https://repronim.wordpress.com/

•	Sign up for our **mailing list**
Link: https://www.nitrc.org/mailman/listinfo/repronim-announcement

•	To report site errors, please file an issue at our **github repo**
Link:  https://github.com/ReproNim/repronim.github.io  
 
•	Explore, Use, and Contribute to our **Training Resources**
Link: https://dev.repronim.org/resources/training/

•	Interested in becoming a Collaborator or Service Project? **Contact us**
[Clickable for email, if possible, TO:]  [info@repronim.org](mailto:info@repronim.org)

•	Become a **ReproNim/INCF Fellow**
o	Link: https://dev.repronim.org/fellowship/

•	Follow our **Webinar series**
Link: https://dev.repronim.org/about/webinars/


Calendar

	R**eproNim ‘First Fridays’ Webinar Series** 
o	Webinars occur on the first Friday of every month throughout the academic year

	**ReproNim ‘First Thursdays’ Virtual Office Hou**r
o	Virtual Drop-in Office Hours occurs on the first Thursday of every month throughout the year

**Comment by asmacdo** [comment]
@juliebates this works for me. Let me know if it came out the way you'd like.

FWIW, what you've got here is very close to the actual syntax, in case its helpful, I've put the syntax below so you can see how close you are.

A couple things that made it a little awkward (very easy to fix, but you seem interested)
 - there are non-renderable characters in front of the 2 repronim calender events, I think they are just google-doc style bullets. In markdown you can use a hyphen or a star.
 - The link syntax is `[visable text](link)` 

```
- [Contact us](mailto:info@repronim.org)
- [The ReproNim Blog](https://repronim.wordpress.com/)
- Sign up for our [mailing list](https://www.nitrc.org/mailman/listinfo/repronim-announcement)
- To report site errors, please file an issue at our [github repo](https://github.com/ReproNim/repronim.org)
- Explore, Use, and Contribute to our [Training Resources](https://dev.repronim.org/resources/training/)
- Interested in becoming a Collaborator or Service Project? [Contact us](mailto:info@repronim.org)
- Become a [ReproNim/INCF Fellow](https://dev.repronim.org/fellowship/)
- Follow our [Webinar series](https://dev.repronim.org/about/webinars/)

## Calendar

### ReproNim ‘First Fridays’ Webinar Series

Webinars occur on the first Friday of every month throughout the academic year

### ReproNim ‘First Thursdays’ Virtual Office Hour

Virtual Drop-in Office Hours occurs on the first Thursday of every month throughout the year
```
That renders to look like:

- [Contact us](mailto:info@repronim.org)
- [The ReproNim Blog](https://repronim.wordpress.com/)
- Sign up for our [mailing list](https://www.nitrc.org/mailman/listinfo/repronim-announcement)
- To report site errors, please file an issue at our [github repo](https://github.com/ReproNim/repronim.org)
- Explore, Use, and Contribute to our [Training Resources](https://dev.repronim.org/resources/training/)
- Interested in becoming a Collaborator or Service Project? [Contact us](mailto:info@repronim.org)
- Become a [ReproNim/INCF Fellow](https://dev.repronim.org/fellowship/)
- Follow our [Webinar series](https://dev.repronim.org/about/webinars/)

## Calendar

### ReproNim ‘First Fridays’ Webinar Series

Webinars occur on the first Friday of every month throughout the academic year

### ReproNim ‘First Thursdays’ Virtual Office Hour

Virtual Drop-in Office Hours occurs on the first Thursday of every month throughout the year
