### ISSUE TITLE
Participate -quick followup question

### ISSUE THREAD

**Issue by juliebates** [ReproNim/repronim.org#84]
Thank you for posting the Participate section - and also thank you for the syntax info, you're right, I am interested in that, and actually kind of reassured that it wasn't too far off, but I like the simple actual syntax.

Just one modification if easy and you have time, to make things a bit more distinct - but just consider your time, can be ok as is:

Under the Calendar section, would it be possible to just reduce the line spacing between each of the twobold-faced item headers and their respective information statements that follows such as (a) below - OR add an indentation for each of the information statements.  (btw, Yes- you're right, the non-renderable characters in that section were (word doc style) bullets!). I didn't put anything in syntax below, (and I don't actually know how to show intentional line spacing gaps) but I was just trying to show visually what I meant by creating a bit of visual space.

(a)
ReproNim ‘First Fridays’ Webinar Series
Webinars occur on the first Friday of every month throughout the academic year

ReproNim ‘First Thursdays’ Virtual Office Hour
Virtual Drop-in Office Hours occurs on the first Thursday of every month throughout the year

I have a meeting shortly, so will be on something else for a little bit, back on thereafter. Thanks!

**Comment by asmacdo** [comment]
https://github.com/ReproNim/repronim.org/issues/84
https://github.com/ReproNim/repronim.org/pull/88

@juliebates The spacing was because I made each item a heading section, by removing the headings and just using bold directly, I think I've got what you want. Could you please have a look before I merge?

https://deploy-preview-88--repronim.netlify.app/participate/#calendar

![image](https://github.com/user-attachments/assets/c98fbb14-9eae-47db-9c59-81734e605804)

**Comment by juliebates** [comment]
Yes, that looks great - thank you! 
Actually I do things (that I don't understand!) with headers in html on the current site to try and fenegle some spacing without really knowing what I'm doing, so what you did to accomplish this seems a bit familiar  ;-)
